"""add profile fields

Revision ID: 412a88ee3186
Revises: c92117db212d
Create Date: 2026-06-30 12:10:14.313720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412a88ee3186'
down_revision: Union[str, Sequence[str], None] = 'c92117db212d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
