"""change education year to date

Revision ID: 440b8846d055
Revises: 9f00e6015285
Create Date: 2026-09-03 20:38:08.360899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440b8846d055'
down_revision: Union[str, Sequence[str], None] = '9f00e6015285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('candidates', 'resume_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('candidates', 'skills',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('recruiters', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recruiters', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column("educations", "start_year")
    op.drop_column("educations", "end_year")

    op.add_column(
        "educations",
        sa.Column("start_date", sa.Date(), nullable=True)
    )

    op.add_column(
        "educations",
        sa.Column("end_date", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recruiters', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('recruiters', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'skills',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('candidates', 'resume_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('candidates', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column("educations", "start_date")
    op.drop_column("educations", "end_date")

    op.add_column(
        "educations",
        sa.Column("start_year", sa.Integer(), nullable=True)
    )

    op.add_column(
        "educations",
        sa.Column("end_year", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###
