"""add is_deleted to applications

Revision ID: a24ebaf3e3fa
Revises: 412a88ee3186
Create Date: 2026-07-04 12:13:05.494698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24ebaf3e3fa'
down_revision: Union[str, Sequence[str], None] = '412a88ee3186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'is_deleted')
    # ### end Alembic commands ###
