"""fix job saved_jobs cascade

Revision ID: b32a5e4bc093
Revises: dac0d4ae363a
Create Date: 2026-06-19 19:23:19.736269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32a5e4bc093'
down_revision: Union[str, Sequence[str], None] = 'dac0d4ae363a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
