"""add profile fields

Revision ID: c92117db212d
Revises: 1e234a840581
Create Date: 2026-06-30 11:34:38.769573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92117db212d'
down_revision: Union[str, Sequence[str], None] = '1e234a840581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('experience', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('education', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('resume', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'resume')
    op.drop_column('users', 'education')
    op.drop_column('users', 'experience')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'location')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
